names = { #XXX use property utility names instead
    'cut': 'Cut',
    'slice': 'Slice',
    'inset': 'Inset',
    'intersect': 'Intersect',
    'join': 'Join',
    'make': 'Make',
    'knife': 'Knife',
    'extract': 'Extract',
    'simple_topbar': 'Simple Topbar',
    'snap': 'Snap',
    'negative': 'Negative',
    'bbox': 'Bbox',
    'tab': 'Tab',
    'snap_point': 'Snap point',
    'snap_point_highlight': 'Highlight',
    'dot': 'Dot',
    'dot_bevel': 'Bevel Dot',
    'dot_highlight': 'Dot Highlight',
    'wire': 'Wire',
    'grid': 'Grid',
    'grid_use_mode': 'Grid Mode Color',
    'grid_wire': 'Grid Wire',
    'show_shape_wire': 'Show Shape Wire',
    'wire_width': 'Wire Width',
    'stipple_width': 'Stipple Width',
    'bounds': 'Show Bounds',
    'allow_selection': 'Allow Selection',
    'sort_modifiers': 'Sort Modifiers',
    'keep_modifiers': 'Keep Modifiers',
    'rotate_angle': 'Rotate Snap Angle',
    'ngon_angle': 'Ngon Snap Angle',
    'auto_smooth': 'Auto Smooth',
    'join_flip_z': 'Join Flip Z',
    'make_active': 'Shift to Active',
    'line_box': 'Line Box',
    'line_box_angle': 'Line Angle',
    'hops_mark': 'HOps Mark',
    'set_origin': 'Set Origin',
    'show_shape': 'Show Shape',
    'parent_shape': 'Parent Shape',
    'apply_slices': 'Apply Slices',
    'recut': 'Recut',
    'wedge': 'Wedge',
    'show_wire': 'Show Wire',
    'apply_scale': 'Apply Scale',
    'make_align_z': 'Make on Z',
    'offset': 'Offset',
    'destructive_menu': 'Destructive Menu',
    'mode_label': 'Mode Label',
    'shape_label': 'Shape Label',
    'operation_label': 'Operation Label',
    'surface_label': 'Surface Label',
    'wire_only': 'Wires Only',
    'thick_wire': 'Thick Wire',
    'circle_vertices': 'Circle Vertices',
    'bevel_width': 'Bevel Width',
    'bevel_segments': 'Bevel Segments',
    'quad_bevel': 'Quad Bevel',
    'straight_edges': 'Straight Corner Flow',
    'inset_thickness': 'Inset Thickness',
    'solidify_thickness': 'Solidify Thickness',
    'array_count': 'Array Count',
    'lazorcut_limit': 'Lazorcut Limit',
    'lazorcut_depth': 'Depth',
    'quick_execute': 'Quick Execute',
    'auto_ortho': 'Auto Ortho',
    'lazorcut_trim': 'Accucut Lazorcut',
    'simple_trace': 'Simple Trace',
    'edit_disable_modifiers': 'Disable Ctrl & Shift LMB (Edit Mode)',
    'enable_surface_toggle': 'Enable Surface Toggle',
    'cursor': 'Cursor',
    'cycle_all': 'Cycle All Cutters',
    'grid_gizmo': 'Grid Gizmo',
    'transform_gizmo': 'Transform Gizmo',
    'reduce_opacity_editmode': 'Reduce Opacity in Edit',
    'scroll_adjust_circle': 'Scroll Adjust Circle',
    'axis': 'Cursor Axis',
    'array_axis': 'Array Axis',
    'array_around_cursor': 'Array Around 3D Cursor',
    'rotate_axis': 'Rotate Axis',
    'dots': 'Display Dot Gizmos'}
